### ISSUE TITLE
Overview: Improvements

### ISSUE THREAD

**Issue by ungatoverde** [best-cost/best-cost_WPs#101]
Until 07 April 2025

# [Function documentation](https://github.com/best-cost/best-cost_WPs/issues/454)
- [x] #455 
- [x] #456 
- [x] #459 
- [x] #460 
- [x] #467 

# [testing vignette](https://github.com/best-cost/best-cost_WPs/issues/444)
- [x] #452 

# [intro vignette](https://github.com/best-cost/best-cost_WPs/issues/449)
- [x] #462

# [Bug fixing](https://github.com/best-cost/best-cost_WPs/issues/472)
- [x] #471 
# [Summary uncertainty](https://github.com/best-cost/best-cost_WPs/issues/457)
- [x] #458 
- [x] #461 

# Optimization of the code (performance)

# Other (small) changes
- [x] #463 

# Rename of variables and functions
- [x] #478

**Comment by ungatoverde** [comment]
Until 2 December

# Bug fixing
- [x] #332 (AL)
- [x] Identical results in geographic iteration of attribute_health() #318. Done in #337 
- [x] In` compile_input()`, `bhd_lower` is duplicated and should be replaced with `bhd_higher`. Done in #337 
- [x] If the impact is the same in scenario 1 and scenario 2, impact will be identified as joining column and should not be the case (the same applies to pop_fraction...). Done in #344 
- [x] The cutoff should actually move the user-defined erf equation to the right.
- [x] If `attribute` is called with the argument `corrected_discount_rate` set to any value (0, 0.5, ...) the output has > 1000 rows

# Other (small) changes
- [x] #329 (AL). Done in #350 
- [x] Potential incompatibilities with R base pipes. See #305 
- [x] Rename R package. See [https://www.njtierney.com/post/2017/10/27/change-pkg-name/](https://www.njtierney.com/post/2017/10/27/change-pkg-name/)
- [x] Include `population_total` and `popultion_exposed` as arguments of attribute_ functions, ie. voluntary previous step to proportion of population exposed (either one or the other). Done in #349
