### ISSUE TITLE
Overview: New features

### ISSUE THREAD

**Issue by ungatoverde** [best-cost/best-cost_WPs#121]
Let's collect here a to-dos that are relative with (major) enhancements of the R package. If discussion is needed in any of the items, feel free to open a specific issue

**Comment by ungatoverde** [comment]
Until 2 November 2024
- [x] Implement approaches for quantifying social inequality (AL) #307
- [x] Social inequalities with decile approach (ACF) #341 
- [x] Add possibility to add central, lower and upper 95% CI functions at once using user-defined points (currently only 1 central function can be eneted)
- [x] Include health impact per exposure category in output #325 (ACF)
- [x] #330 (ACF) Done in #349 and #350
- [x] Absolute risk integrated into `attribute_health`. (ACF) Done in #350 
- [x] Rates instead of population in exposure categories as input data #333 (ACF). Done in #349
