### ISSUE TITLE
Name of variables (and functions)

### ISSUE THREAD

**Issue by ungatoverde** [best-cost/best-cost_WPs#61]
Some names of variables of external and internal functions could be improved

Linked branch:  [Variable_names](https://github.com/best-cost/best-cost_WPs/tree/Variable_names)

For instance
- [x] `year` or `year_of_analysis` instead of `firstYear_lifetable`
- [ ] `age_group_at_risk` instead of `age_group`?
- [ ]  `pop_impact` instead of `shifted_popOverTime`. This now the result of a function called `bestcost::get_pop_impact()`
- [x] `lifetable_withPop` instead of `lifetable_wPop` in `bestcost::get_popOverTime_noAP()`
- [ ] `age_start` instead `age` (in contrast to `age_end` column)
- [x] The info variables (e.g. `exp_info`, `cf_info`, `bhd_info`, `crf_info`) are not necessary for the calculation. They are only extra columns to show additional information in the final output table. They should start with `info_` to intinstively see them as in the same `info_` category. See merged branch #85 
- [ ] `_detailed` instead of `_long`
- [x] either `paf` or `af` but we should be consistent. See #95 
- [x] # "pep" might be renamed. See #99 
- [x] # "crfConc" might be renamed to ... See #99 

@luytax Feel free to add here some other examples so that we do not forget them
