### ISSUE TITLE
Simplification of the code

### ISSUE THREAD

**Issue by ungatoverde** [best-cost/best-cost_WPs#63]
To improve the performance of the package functions it is always good to simplify the coding style/structure.

@luytax Let's compile here some ideas.

- [x] I think that we do not need the condition [here](https://github.com/best-cost/best-cost_WPs/blob/29bf1c3259dcd0199baf169499152c2449198941/r_package/bestcost/R/get_popSingleYear_withAP.R#L33-L47) for the infants. We could do the same for infants and adults because we later only consider the deaths and YLLs for `age_max` for infants. 
- [x] The function `assess_mortality_lifetable()` and `assess_impact_single()` should not need `age_group` as input. `Age_group` do not determine anything in the calculation. See branch merge #78 
- [x] Similarly to `age_group`, the calculation does not depend on `outcome_group` and can be removed as variable. See branch merge #87 
- [x] Remove method "ap10". It was only relevant for the external cost of transport in CH. See branch merge #89 
- [x] Replace `impact_per_unit` with `impact_beforeRounding` so that you avoid a later rename. See branch merge #89 
- [x] Age range can be done before `get_deaths()` and `get_yll` in the meta-information data frame. This saves some duplicated code. See branch merge #91 
- [x] left_join is duplicated in `get_yll()`  (see [code](https://github.com/best-cost/best-cost_WPs/blob/842303da82fbcac4ae1d026098ab29fdf0a3e5d6/r_package/bestcost/R/get_yll.R#L68-L71)). Do it only once and then split into discounted and not discounted. See branch merge #97
